### ISSUE TITLE
“/setprofile" route is likely to mistakenly set other's profiles

### ISSUE THREAD

**Issue by XcloudFance** [XcloudFance/Fakebook#5]
### Problem Statement
“/setprofile" route is likely to mistakenly set other's profiles

### Solution
After authenticate, use the token to find corresponding user. If the request user token doesnt match the user token that it is gonna set, return error. @czyu6

**Comment by czyu6** [comment]
I have added authentication in /set_profile to compare the request token in the cookies, with the token of the uid entered.
https://github.com/XcloudFance/Fakebook/pull/6

**Comment by XcloudFance** [comment]
> I have added authentication in /set_profile to compare the request token in the cookies, with the token of the uid entered. #6

Noted with thanks
